server:
  port: 8090
notLogPathStart: "/static,/actuator"
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  file:
    path: D:\logs\${spring.application.name}
  config: classpath:logback-spring.xml